/* DO NOT EDIT *************************************************
 * THIS FILE AUTOMATICALLY GENERATED BY THE es_getproc_gen.py SCRIPT
 * API specification file:   APIspec.txt
 * GLES version:             GLES2.0
 * date:                     2008-10-30 14:40:48
 */


#include <string.h>

/* We need to define this to get prototypes for the extension functions. */
#define GL_GLEXT_PROTOTYPES

#include "GLES2/gl2.h"
#include "GLES2/gl2ext.h"
#include "st_platform.h"


typedef void (*_glapi_proc)(void); /* generic function pointer */
_glapi_proc 
_glapi_get_proc_address(const char *funcName);


static const struct {
   const char *name;
   _glapi_proc proc;
} procs[] = {
    {"glCompressedTexImage3DOES", (_glapi_proc) glCompressedTexImage3DOES}, /* OES_texture_3D */
    {"glCompressedTexSubImage3DOES", (_glapi_proc) glCompressedTexSubImage3DOES}, /* OES_texture_3D */
    {"glCopyTexSubImage3DOES", (_glapi_proc) glCopyTexSubImage3DOES}, /* OES_texture_3D */
    {"glFramebufferTexture3DOES", (_glapi_proc) glFramebufferTexture3DOES}, /* OES_texture_3D */
    {"glGetBufferPointervOES", (_glapi_proc) glGetBufferPointervOES}, /* OES_mapbuffer */
    {"glMapBufferOES", (_glapi_proc) glMapBufferOES}, /* OES_mapbuffer */
    {"glTexImage3DOES", (_glapi_proc) glTexImage3DOES}, /* OES_texture_3D */
    {"glTexSubImage3DOES", (_glapi_proc) glTexSubImage3DOES}, /* OES_texture_3D */
    {"glUnmapBufferOES", (_glapi_proc) glUnmapBufferOES}, /* OES_mapbuffer */
};

_glapi_proc 
_glapi_get_proc_address(const char *funcName)
{
   unsigned int i;
   for (i = 0; i < sizeof(procs)/sizeof(procs[0]); i++) {
      if (!strcmp(funcName, procs[i].name))
         return procs[i].proc;
   }
   return NULL;
}

