/* DO NOT EDIT *************************************************
 * THIS FILE AUTOMATICALLY GENERATED BY THE es_getproc_gen.py SCRIPT
 * API specification file:   APIspec.txt
 * GLES version:             GLES1.1
 * date:                     2008-10-30 14:40:47
 */


#include <string.h>

/* We need to define this to get prototypes for the extension functions. */
#define GL_GLEXT_PROTOTYPES

#include "GLES/gl.h"
#include "GLES/glext.h"
#include "st_platform.h"


typedef void (*_glapi_proc)(void); /* generic function pointer */
_glapi_proc 
_glapi_get_proc_address(const char *funcName);


static const struct {
   const char *name;
   _glapi_proc proc;
} procs[] = {
    {"glAlphaFuncxOES", (_glapi_proc) glAlphaFuncxOES}, /* OES_fixed_point */
    {"glBindFramebufferOES", (_glapi_proc) glBindFramebufferOES}, /* OES_framebuffer_object */
    {"glBindRenderbufferOES", (_glapi_proc) glBindRenderbufferOES}, /* OES_framebuffer_object */
    {"glBlendEquationOES", (_glapi_proc) glBlendEquationOES}, /* OES_blend_subtract */
    {"glBlendEquationSeparateOES", (_glapi_proc) glBlendEquationSeparateOES}, /* OES_blend_equation_separate */
    {"glBlendFuncSeparateOES", (_glapi_proc) glBlendFuncSeparateOES}, /* OES_blend_func_separate */
    {"glCheckFramebufferStatusOES", (_glapi_proc) glCheckFramebufferStatusOES}, /* OES_framebuffer_object */
    {"glClearColorxOES", (_glapi_proc) glClearColorxOES}, /* OES_fixed_point */
    {"glClearDepthfOES", (_glapi_proc) glClearDepthfOES}, /* OES_single_precision */
    {"glClearDepthxOES", (_glapi_proc) glClearDepthxOES}, /* OES_fixed_point */
    {"glClipPlanefOES", (_glapi_proc) glClipPlanefOES}, /* OES_single_precision */
    {"glClipPlanexOES", (_glapi_proc) glClipPlanexOES}, /* OES_fixed_point */
    {"glColor4xOES", (_glapi_proc) glColor4xOES}, /* OES_fixed_point */
    {"glDeleteFramebuffersOES", (_glapi_proc) glDeleteFramebuffersOES}, /* OES_framebuffer_object */
    {"glDeleteRenderbuffersOES", (_glapi_proc) glDeleteRenderbuffersOES}, /* OES_framebuffer_object */
    {"glDepthRangefOES", (_glapi_proc) glDepthRangefOES}, /* OES_single_precision */
    {"glDepthRangexOES", (_glapi_proc) glDepthRangexOES}, /* OES_fixed_point */
    {"glFogxOES", (_glapi_proc) glFogxOES}, /* OES_fixed_point */
    {"glFogxvOES", (_glapi_proc) glFogxvOES}, /* OES_fixed_point */
    {"glFramebufferRenderbufferOES", (_glapi_proc) glFramebufferRenderbufferOES}, /* OES_framebuffer_object */
    {"glFramebufferTexture2DOES", (_glapi_proc) glFramebufferTexture2DOES}, /* OES_framebuffer_object */
    {"glFrustumfOES", (_glapi_proc) glFrustumfOES}, /* OES_single_precision */
    {"glFrustumxOES", (_glapi_proc) glFrustumxOES}, /* OES_fixed_point */
    {"glGenFramebuffersOES", (_glapi_proc) glGenFramebuffersOES}, /* OES_framebuffer_object */
    {"glGenRenderbuffersOES", (_glapi_proc) glGenRenderbuffersOES}, /* OES_framebuffer_object */
    {"glGenerateMipmapOES", (_glapi_proc) glGenerateMipmapOES}, /* OES_framebuffer_object */
    {"glGetBufferPointervOES", (_glapi_proc) glGetBufferPointervOES}, /* OES_mapbuffer */
    {"glGetClipPlanefOES", (_glapi_proc) glGetClipPlanefOES}, /* OES_single_precision */
    {"glGetClipPlanexOES", (_glapi_proc) glGetClipPlanexOES}, /* OES_fixed_point */
    {"glGetFixedvOES", (_glapi_proc) glGetFixedvOES}, /* OES_fixed_point */
    {"glGetFramebufferAttachmentParameterivOES", (_glapi_proc) glGetFramebufferAttachmentParameterivOES}, /* OES_framebuffer_object */
    {"glGetLightxvOES", (_glapi_proc) glGetLightxvOES}, /* OES_fixed_point */
    {"glGetMaterialxvOES", (_glapi_proc) glGetMaterialxvOES}, /* OES_fixed_point */
    {"glGetRenderbufferParameterivOES", (_glapi_proc) glGetRenderbufferParameterivOES}, /* OES_framebuffer_object */
    {"glGetTexEnvxvOES", (_glapi_proc) glGetTexEnvxvOES}, /* OES_fixed_point */
    {"glGetTexGenfvOES", (_glapi_proc) glGetTexGenfvOES}, /* OES_texture_cube_map */
    {"glGetTexGenivOES", (_glapi_proc) glGetTexGenivOES}, /* OES_texture_cube_map */
    {"glGetTexGenxvOES", (_glapi_proc) glGetTexGenxvOES}, /* OES_texture_cube_map */
    {"glGetTexParameterxvOES", (_glapi_proc) glGetTexParameterxvOES}, /* OES_fixed_point */
    {"glIsFramebufferOES", (_glapi_proc) glIsFramebufferOES}, /* OES_framebuffer_object */
    {"glIsRenderbufferOES", (_glapi_proc) glIsRenderbufferOES}, /* OES_framebuffer_object */
    {"glLightModelxOES", (_glapi_proc) glLightModelxOES}, /* OES_fixed_point */
    {"glLightModelxvOES", (_glapi_proc) glLightModelxvOES}, /* OES_fixed_point */
    {"glLightxOES", (_glapi_proc) glLightxOES}, /* OES_fixed_point */
    {"glLightxvOES", (_glapi_proc) glLightxvOES}, /* OES_fixed_point */
    {"glLineWidthxOES", (_glapi_proc) glLineWidthxOES}, /* OES_fixed_point */
    {"glLoadMatrixxOES", (_glapi_proc) glLoadMatrixxOES}, /* OES_fixed_point */
    {"glMapBufferOES", (_glapi_proc) glMapBufferOES}, /* OES_mapbuffer */
    {"glMaterialxOES", (_glapi_proc) glMaterialxOES}, /* OES_fixed_point */
    {"glMaterialxvOES", (_glapi_proc) glMaterialxvOES}, /* OES_fixed_point */
    {"glMultMatrixxOES", (_glapi_proc) glMultMatrixxOES}, /* OES_fixed_point */
    {"glMultiTexCoord4xOES", (_glapi_proc) glMultiTexCoord4xOES}, /* OES_fixed_point */
    {"glNormal3xOES", (_glapi_proc) glNormal3xOES}, /* OES_fixed_point */
    {"glOrthofOES", (_glapi_proc) glOrthofOES}, /* OES_single_precision */
    {"glOrthoxOES", (_glapi_proc) glOrthoxOES}, /* OES_fixed_point */
    {"glPointParameterxOES", (_glapi_proc) glPointParameterxOES}, /* OES_fixed_point */
    {"glPointParameterxvOES", (_glapi_proc) glPointParameterxvOES}, /* OES_fixed_point */
    {"glPointSizePointerOES", (_glapi_proc) glPointSizePointerOES}, /* OES_point_size_array */
    {"glPointSizexOES", (_glapi_proc) glPointSizexOES}, /* OES_fixed_point */
    {"glPolygonOffsetxOES", (_glapi_proc) glPolygonOffsetxOES}, /* OES_fixed_point */
    {"glQueryMatrixxOES", (_glapi_proc) glQueryMatrixxOES}, /* OES_query_matrix */
    {"glRenderbufferStorageOES", (_glapi_proc) glRenderbufferStorageOES}, /* OES_framebuffer_object */
    {"glRotatexOES", (_glapi_proc) glRotatexOES}, /* OES_fixed_point */
    {"glSampleCoveragexOES", (_glapi_proc) glSampleCoveragexOES}, /* OES_fixed_point */
    {"glScalexOES", (_glapi_proc) glScalexOES}, /* OES_fixed_point */
    {"glTexEnvxOES", (_glapi_proc) glTexEnvxOES}, /* OES_fixed_point */
    {"glTexEnvxvOES", (_glapi_proc) glTexEnvxvOES}, /* OES_fixed_point */
    {"glTexGenfOES", (_glapi_proc) glTexGenfOES}, /* OES_texture_cube_map */
    {"glTexGenfvOES", (_glapi_proc) glTexGenfvOES}, /* OES_texture_cube_map */
    {"glTexGeniOES", (_glapi_proc) glTexGeniOES}, /* OES_texture_cube_map */
    {"glTexGenivOES", (_glapi_proc) glTexGenivOES}, /* OES_texture_cube_map */
    {"glTexGenxOES", (_glapi_proc) glTexGenxOES}, /* OES_texture_cube_map */
    {"glTexGenxvOES", (_glapi_proc) glTexGenxvOES}, /* OES_texture_cube_map */
    {"glTexParameterxOES", (_glapi_proc) glTexParameterxOES}, /* OES_fixed_point */
    {"glTexParameterxvOES", (_glapi_proc) glTexParameterxvOES}, /* OES_fixed_point */
    {"glTranslatexOES", (_glapi_proc) glTranslatexOES}, /* OES_fixed_point */
    {"glUnmapBufferOES", (_glapi_proc) glUnmapBufferOES}, /* OES_mapbuffer */
};

_glapi_proc 
_glapi_get_proc_address(const char *funcName)
{
   unsigned int i;
   for (i = 0; i < sizeof(procs)/sizeof(procs[0]); i++) {
      if (!strcmp(funcName, procs[i].name))
         return procs[i].proc;
   }
   return NULL;
}

