FRAG

DCL IN[0], COLOR, LINEAR
DCL OUT[0], COLOR
DCL TEMP[0..1]

F2D TEMP[0], IN[0]
F2D TEMP[1], IN[0].zwzw
DMUL TEMP[0], TEMP[0], TEMP[0]
DMUL TEMP[1], TEMP[1], TEMP[1]
DSQRT TEMP[0], TEMP[0]
DSQRT TEMP[1], TEMP[1]
D2F OUT[0].xy, TEMP[0]
D2F TEMP[1].xy, TEMP[1]
MOV OUT[0].zw, TEMP[1].xyxy

END
