FRAG

DCL IN[0], COLOR, LINEAR
DCL OUT[0], COLOR
DCL TEMP[0..1]

F2D TEMP[0], IN[0]
F2D TEMP[1], IN[0].zwzw
D2F TEMP[0].xy, TEMP[0]
D2F TEMP[1].xy, TEMP[1]
MOV OUT[0].xy, TEMP[0]
MOV OUT[0].zw, TEMP[1].xyxy

END
